# Generated by Django 5.1.15 on 2026-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_status', models.CharField(choices=[('ok', 'ok'), ('unavailable', 'unavailable')], max_length=12)),
                ('service_status', models.CharField(choices=[('ok', 'ok'), ('unavailable', 'unavailable')], max_length=12)),
                ('document_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
